import { Product, Order, TopSupplier, User } from './types';

export const INITIAL_USERS: Record<string, User> = {
  shopkeeper: {
    id: 'usr_shop_1',
    name: 'M. Hassan',
    email: 'hassan.traders@gmail.com',
    phone: '+92 321 4567890',
    role: 'shopkeeper',
    businessName: 'Hassan Wholesale Mart',
    city: 'Karachi',
    ntn: '8945123-4',
    category: 'Rice & Grains, Spices',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&h=150&fit=crop',
    verified: true,
  },
  supplier: {
    id: 'usr_supp_1',
    name: 'Ahmed Khan',
    email: 'ahmed@akenterprises.pk',
    phone: '+92 300 1234567',
    role: 'supplier',
    businessName: 'Ahmed Khan Enterprises',
    city: 'Lahore',
    ntn: '1234567-8',
    category: 'Rice & Grains, Spices, Textiles',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    verified: true,
  }
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Basmati Rice Premium Super Kernel (Grade A)',
    category: 'Rice & Grains',
    price: 4500,
    unit: '50kg bag',
    moq: 10,
    stock: 850,
    supplierId: 'usr_supp_1',
    supplierName: 'Punjab Agri Exports',
    supplierCity: 'Sheikhupura',
    supplierVerified: true,
    rating: 4.8,
    reviewCount: 234,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=640&h=640&fit=crop',
    description: 'Aromatic extra long grain super kernel basmati rice aged for 12 months. Ideal for commercial restaurants, catering, and wholesale distribution across Pakistan.',
    ordersCount: 124,
    status: 'Active',
    isTrending: true,
    aiReason: 'High demand in your region this season (Punjab & Sindh)'
  },
  {
    id: 'prod_2',
    name: 'Lahori Red Chilli Powder (Steam Sterilized)',
    category: 'Spices',
    price: 2200,
    unit: '5kg pack',
    moq: 5,
    stock: 320,
    supplierId: 'usr_supp_2',
    supplierName: 'Multan Masala House',
    supplierCity: 'Multan',
    supplierVerified: true,
    rating: 4.6,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=640&h=640&fit=crop',
    description: '100% pure organic red chilli powder ground from sun-dried whole chillies. Rich natural color and intense pungency with zero artificial coloring.',
    ordersCount: 89,
    status: 'Active',
    isTrending: true,
    aiReason: 'Popular with customers who ordered Basmati Rice'
  },
  {
    id: 'prod_3',
    name: 'Cotton Fabric White Shirting (Export Quality)',
    category: 'Textiles',
    price: 850,
    unit: '100m roll',
    moq: 10,
    stock: 4500,
    supplierId: 'usr_supp_3',
    supplierName: 'Faisalabad Textile Mills',
    supplierCity: 'Faisalabad',
    supplierVerified: true,
    rating: 4.9,
    reviewCount: 412,
    image: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=640&h=640&fit=crop',
    description: 'Premium comb cotton fabric 60/60 weave, crisp white finish with high durability and soft breathability for garment manufacturing.',
    ordersCount: 203,
    status: 'Active',
    isTrending: true,
    aiReason: 'Trending among Karachi wholesale apparel markets'
  },
  {
    id: 'prod_4',
    name: 'Desi Ghee Pure Buffalo (Traditional Bilona)',
    category: 'Dairy',
    price: 3800,
    unit: '5kg tin',
    moq: 5,
    stock: 120,
    supplierId: 'usr_supp_4',
    supplierName: 'Gujranwala Dairy Farm',
    supplierCity: 'Gujranwala',
    supplierVerified: true,
    rating: 4.5,
    reviewCount: 98,
    image: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?w=640&h=640&fit=crop',
    description: 'Pure, golden, aromatic desi ghee crafted using traditional churning methods. Lab-tested purity with zero preservatives.',
    ordersCount: 76,
    status: 'Low Stock',
    isTrending: false,
    aiReason: 'Seasonal peak approaching next month'
  },
  {
    id: 'prod_5',
    name: 'Himalayan Pink Rock Salt (Food Grade Coarse)',
    category: 'Minerals',
    price: 180,
    unit: '50kg bag',
    moq: 20,
    stock: 2400,
    supplierId: 'usr_supp_5',
    supplierName: 'Khewra Salt Mines Co.',
    supplierCity: 'Khewra',
    supplierVerified: true,
    rating: 4.7,
    reviewCount: 567,
    image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=640&h=640&fit=crop',
    description: 'Natural unrefined Himalayan pink salt packed with 84 essential minerals directly sourced from Khewra mines.',
    ordersCount: 310,
    status: 'Active',
    isTrending: true,
    aiReason: '4,820 wholesale searches recorded this week'
  },
  {
    id: 'prod_6',
    name: 'Sindhi Red Onions Premium (Grade 1)',
    category: 'Vegetables',
    price: 120,
    unit: '100kg crate',
    moq: 10,
    stock: 950,
    supplierId: 'usr_supp_6',
    supplierName: 'Hyderabad Fresh Farms',
    supplierCity: 'Hyderabad',
    supplierVerified: true,
    rating: 4.4,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=640&h=640&fit=crop',
    description: 'Freshly harvested firm red onions from Sindh farm fields. Excellent storage life and strong pungent aroma.',
    ordersCount: 92,
    status: 'Active',
    isTrending: false,
    aiReason: 'High turnover rate in daily mandis'
  },
  {
    id: 'prod_7',
    name: 'Sunflower Cooking Oil (Refined Pure 15L)',
    category: 'Dairy & Oils',
    price: 5200,
    unit: '15L Can',
    moq: 10,
    stock: 650,
    supplierId: 'usr_supp_7',
    supplierName: 'Lahore Oils Ltd.',
    supplierCity: 'Lahore',
    supplierVerified: true,
    rating: 4.8,
    reviewCount: 320,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=640&h=640&fit=crop',
    description: 'Triple-refined vitamin A & D enriched 100% sunflower cooking oil for industrial and commercial kitchens.',
    ordersCount: 184,
    status: 'Active',
    isTrending: true,
    aiReason: 'High demand in your region this season'
  },
  {
    id: 'prod_8',
    name: 'Refined Sugar Crystal White 50kg',
    category: 'Rice & Grains',
    price: 6800,
    unit: '50kg bag',
    moq: 15,
    stock: 1500,
    supplierId: 'usr_supp_8',
    supplierName: 'Mirpur Khas Sugar Mills',
    supplierCity: 'Mirpur Khas',
    supplierVerified: true,
    rating: 4.6,
    reviewCount: 210,
    image: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?w=640&h=640&fit=crop',
    description: 'Grade 1 refined white crystalline cane sugar with sparkling purity and instant solubility.',
    ordersCount: 145,
    status: 'Active',
    isTrending: false,
    aiReason: 'You ordered similar staple products 3 months ago'
  },
  {
    id: 'prod_9',
    name: 'Wheat Flour Maida Super Fine 50kg',
    category: 'Rice & Grains',
    price: 3200,
    unit: '50kg bag',
    moq: 15,
    stock: 2100,
    supplierId: 'usr_supp_9',
    supplierName: 'Rawalpindi Flour Mills',
    supplierCity: 'Rawalpindi',
    supplierVerified: true,
    rating: 4.7,
    reviewCount: 388,
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=640&h=640&fit=crop',
    description: 'Double-sifted high gluten wheat flour ideal for bakeries, tandoors, and confectionery production.',
    ordersCount: 260,
    status: 'Active',
    isTrending: true,
    aiReason: 'Trending among Karachi & Lahore shopkeepers'
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_1',
    orderNumber: 'AT-2026-001',
    buyerId: 'usr_shop_1',
    buyerName: 'Karachi Traders Co.',
    buyerRole: 'shopkeeper',
    supplierId: 'usr_supp_1',
    supplierName: 'Punjab Agri Exports',
    items: [
      {
        productId: 'prod_1',
        productName: 'Basmati Rice Premium Super Kernel (Grade A)',
        productImage: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=640&h=640&fit=crop',
        unitPrice: 4500,
        quantity: 50,
        unit: '50kg bag',
        supplierName: 'Punjab Agri Exports'
      }
    ],
    subtotal: 225000,
    platformFee: 3375,
    totalAmount: 228375,
    status: 'Delivered',
    createdAt: '2026-07-01T10:30:00Z',
    deliveryDate: '2026-07-04T15:00:00Z',
    shippingAddress: 'Plot 45, Jodia Bazaar, Wholesale Market, Karachi',
    paymentMethod: 'JazzCash',
    paymentStatus: 'Paid'
  },
  {
    id: 'ord_2',
    orderNumber: 'AT-2026-002',
    buyerId: 'usr_shop_1',
    buyerName: 'Lahore Wholesale Hub',
    buyerRole: 'shopkeeper',
    supplierId: 'usr_supp_3',
    supplierName: 'Faisalabad Textile Mills',
    items: [
      {
        productId: 'prod_3',
        productName: 'Cotton Fabric White Shirting (Export Quality)',
        productImage: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=640&h=640&fit=crop',
        unitPrice: 850,
        quantity: 800,
        unit: '100m roll',
        supplierName: 'Faisalabad Textile Mills'
      }
    ],
    subtotal: 680000,
    platformFee: 10200,
    totalAmount: 690200,
    status: 'Shipped',
    createdAt: '2026-06-28T09:15:00Z',
    deliveryDate: '2026-07-06T12:00:00Z',
    shippingAddress: 'Shop 12, Azam Cloth Market, Lahore',
    paymentMethod: 'Bank Transfer',
    paymentStatus: 'Paid'
  },
  {
    id: 'ord_3',
    orderNumber: 'AT-2026-003',
    buyerId: 'usr_shop_1',
    buyerName: 'Multan Spice Mart',
    buyerRole: 'shopkeeper',
    supplierId: 'usr_supp_2',
    supplierName: 'Multan Masala House',
    items: [
      {
        productId: 'prod_2',
        productName: 'Lahori Red Chilli Powder (Steam Sterilized)',
        productImage: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=640&h=640&fit=crop',
        unitPrice: 2200,
        quantity: 30,
        unit: '5kg pack',
        supplierName: 'Multan Masala House'
      }
    ],
    subtotal: 66000,
    platformFee: 990,
    totalAmount: 66990,
    status: 'Confirmed',
    createdAt: '2026-06-27T14:45:00Z',
    deliveryDate: '2026-07-08T18:00:00Z',
    shippingAddress: 'Galla Mandi Road, Multan',
    paymentMethod: 'EasyPaisa',
    paymentStatus: 'Paid'
  }
];

export const TOP_SUPPLIERS: TopSupplier[] = [
  {
    id: 'supp_1',
    name: 'Punjab Agri Exports',
    initials: 'PA',
    rating: 4.9,
    ordersCount: 24,
    tradeVolume: 1080000,
    verified: true
  },
  {
    id: 'supp_2',
    name: 'Multan Masala House',
    initials: 'MM',
    rating: 4.8,
    ordersCount: 18,
    tradeVolume: 396000,
    verified: true
  },
  {
    id: 'supp_3',
    name: 'Faisalabad Textile Mills',
    initials: 'FT',
    rating: 4.9,
    ordersCount: 15,
    tradeVolume: 765000,
    verified: true
  },
  {
    id: 'supp_4',
    name: 'Khewra Salt Mines Co.',
    initials: 'KS',
    rating: 4.7,
    ordersCount: 31,
    tradeVolume: 279000,
    verified: true
  }
];

export const MONTHLY_SPENDING_SAVINGS = [
  { month: 'Jan', spent: 180000, savings: 24000 },
  { month: 'Feb', spent: 240000, savings: 38000 },
  { month: 'Mar', spent: 195000, savings: 29000 },
  { month: 'Apr', spent: 310000, savings: 52000 },
  { month: 'May', spent: 280000, savings: 41000 },
  { month: 'Jun', spent: 420000, savings: 68000 },
  { month: 'Jul', spent: 480000, savings: 79000 },
];

export const SUPPLIER_REVENUE_CHART = [
  { month: 'Jan', revenue: 320000, orders: 42 },
  { month: 'Feb', revenue: 410000, orders: 58 },
  { month: 'Mar', revenue: 380000, orders: 51 },
  { month: 'Apr', revenue: 520000, orders: 74 },
  { month: 'May', revenue: 490000, orders: 69 },
  { month: 'Jun', revenue: 640000, orders: 92 },
  { month: 'Jul', revenue: 720000, orders: 110 },
];

export const AI_DEMAND_FORECAST = [
  { day: 'D1', actual: 64, forecast: 66, lower: 60, upper: 72 },
  { day: 'D5', actual: 68, forecast: 71, lower: 64, upper: 78 },
  { day: 'D10', actual: 67, forecast: 69, lower: 62, upper: 76 },
  { day: 'D15', actual: 82, forecast: 80, lower: 72, upper: 88 },
  { day: 'D20', actual: null, forecast: 86, lower: 77, upper: 95 },
  { day: 'D25', actual: null, forecast: 91, lower: 81, upper: 101 },
  { day: 'D30', actual: null, forecast: 96, lower: 85, upper: 107 },
];

export const SALES_BY_CATEGORY = [
  { name: 'Textiles', value: 35, color: '#0B3D2E' },
  { name: 'Spices', value: 25, color: '#1A6B4A' },
  { name: 'Rice & Grains', value: 20, color: '#27AE7A' },
  { name: 'Chemicals & Minerals', value: 12, color: '#E09B2D' },
  { name: 'Electronics', value: 8, color: '#3B82F6' },
];

export const CATEGORIES_LIST = [
  { id: 'all', name: 'All Categories', icon: 'Sparkles' },
  { id: 'rice-grains', name: 'Rice & Grains', icon: 'Wheat', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=300&fit=crop' },
  { id: 'spices', name: 'Spices & Masala', icon: 'Flame', image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=300&fit=crop' },
  { id: 'textiles', name: 'Textiles & Fabric', icon: 'Layers', image: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=400&h=300&fit=crop' },
  { id: 'dairy', name: 'Dairy & Ghee', icon: 'Milk', image: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?w=400&h=300&fit=crop' },
  { id: 'minerals', name: 'Himalayan Minerals & Salt', icon: 'Gem', image: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?w=400&h=300&fit=crop' },
  { id: 'vegetables', name: 'Fresh Mandi Produce', icon: 'Apple', image: 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=400&h=300&fit=crop' },
];